//! Property-based tests for the diff engine's algebraic invariants.
//!
//! These generate arbitrary JSON-shaped `serde_json::Value`s (nulls, bools,
//! ints spanning both `i64` and `u64`-only representable ranges, finite
//! floats, unicode strings, and nested arrays/objects) bounded well under
//! [`onix_core::DEFAULT_MAX_DEPTH`] (`512`) — this module caps generated
//! nesting at [`MAX_GENERATED_DEPTH`] so the recursion-depth guard is never
//! exercised here; that guard has its own dedicated, exhaustive coverage in
//! `diff.rs`'s unit tests — and check invariants that must hold for *any*
//! input, not just the hand-picked examples in the unit test suites:
//! reflexivity, that every reported path actually resolves in its expected
//! side, that each report category's membership rules hold, and that a
//! report is deterministic, including independent of `serde_json::Map`'s
//! internal key insertion order.
//!
//! # Why keys here exclude quotes, backslashes, and control characters
//!
//! `path::quote_key` (see its doc, and the golden corpus) does not
//! escape anything — it only chooses which quote character to wrap a key
//! in, based solely on whether the key contains a single quote. Dict keys
//! generated by [`arb_key`] still exclude quotes, backslashes, and control
//! characters, not because `quote_key` would mangle them, but so
//! [`parse_path`] — a small, hand-rolled reverse of
//! [`onix_core::path::render_path`] — can find each key segment's closing
//! quote unambiguously (the first `'`/`"` after `[` is always the one
//! `quote_key` inserted to close it) without reimplementing `quote_key`'s
//! quote-character-choice logic in reverse. That logic itself is already
//! exhaustively unit-tested in `path.rs`; the goal here is different —
//! checking that reported paths resolve and that category membership rules
//! hold across arbitrary *values*, not re-proving `quote_key`'s own
//! correctness.
//!
//! # Reproducibility
//!
//! All properties share one [`config`] with a fixed [`RngSeed`] and a fixed
//! case count, so a run always explores the identical sequence of generated
//! values — any failure reproduces deterministically, the whole point of a
//! fixed seed — and `make check` stays fast.

use proptest::prelude::*;
use proptest::test_runner::{Config, RngSeed, TestCaseError};
use serde_json::{Map, Number, Value};

use onix_core::diff;

/// Recursion bound for generated values: far below
/// [`onix_core::DEFAULT_MAX_DEPTH`] (`512`), so the depth guard is never
/// exercised by these tests.
const MAX_GENERATED_DEPTH: u32 = 6;

/// Rough cap on the total number of nodes `prop_recursive` aims for per
/// generated value.
const MAX_GENERATED_NODES: u32 = 64;

/// Cap on elements per generated array/object, keeping cases small and fast.
const MAX_COLLECTION_BRANCH: u32 = 6;

/// Cap on proptest cases per property, keeping `make check` fast.
const PROPTEST_CASES: u32 = 256;

/// Fixed seed so every run explores the identical sequence of generated
/// values (see this module's doc).
const PROPTEST_SEED: u64 = 0x0451_1745_0999_0001;

/// The shared [`Config`] every property in this file runs under.
fn config() -> Config {
    Config {
        cases: PROPTEST_CASES,
        rng_seed: RngSeed::Fixed(PROPTEST_SEED),
        ..Config::default()
    }
}

/// A dict key that never needs [`onix_core::path::quote_key`] escaping (no
/// quote, backslash, or C0/DEL control character) — see this module's doc
/// for why. Still exercises unicode (any character outside that excluded
/// set is allowed).
fn arb_key() -> impl Strategy<Value = String> {
    r#"[^'"\\\x00-\x1f\x7f]{0,8}"#
}

/// A single JSON leaf: null, bool, int (spanning both `i64` and
/// `u64`-only-representable ranges), finite float, or unicode string.
fn arb_json_leaf() -> impl Strategy<Value = Value> {
    let u64_only_range = (i64::MAX as u64 + 1)..=u64::MAX;
    prop_oneof![
        Just(Value::Null),
        any::<bool>().prop_map(Value::Bool),
        any::<i64>().prop_map(|n| Value::Number(Number::from(n))),
        u64_only_range.prop_map(|n| Value::Number(Number::from(n))),
        any::<f64>()
            .prop_filter("JSON has no NaN/Infinity", |f| f.is_finite())
            .prop_map(|f| Value::Number(Number::from_f64(f).expect("filtered to finite above"))),
        ".*".prop_map(Value::String),
    ]
}

/// An arbitrary JSON-shaped value: a leaf, or an array/object recursing into
/// more of the same, bounded to [`MAX_GENERATED_DEPTH`].
fn arb_json_value() -> impl Strategy<Value = Value> {
    arb_json_leaf().prop_recursive(
        MAX_GENERATED_DEPTH,
        MAX_GENERATED_NODES,
        MAX_COLLECTION_BRANCH,
        |inner| {
            prop_oneof![
                prop::collection::vec(inner.clone(), 0..MAX_COLLECTION_BRANCH as usize)
                    .prop_map(Value::Array),
                prop::collection::hash_map(arb_key(), inner, 0..MAX_COLLECTION_BRANCH as usize)
                    .prop_map(|map| Value::Object(map.into_iter().collect())),
            ]
        },
    )
}

/// One parsed step of a DeepDiff-style path: a dict key or a list index.
#[derive(Debug)]
enum PathStep {
    Key(String),
    Index(usize),
}

/// Parses a DeepDiff-style path string (e.g. `root['a'][0]`) produced by
/// [`onix_core::path::render_path`] back into [`PathStep`]s.
///
/// Deliberately only handles the single-quote-free key subset [`arb_key`]
/// produces (see this module's doc) — it is not a general-purpose reverse
/// of `path::quote_key`, which has its own exhaustive coverage in
/// `path.rs`. Because generated keys never contain a single quote, a
/// key segment's closing quote is unambiguous: the first `'` encountered
/// after `['` is always the one `quote_key` inserted to close it.
fn parse_path(path: &str) -> Vec<PathStep> {
    let rest = path
        .strip_prefix("root")
        .expect("every rendered path starts with \"root\"");

    let bytes = rest.as_bytes();
    let mut steps = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        assert_eq!(bytes[i], b'[', "malformed path segment in {path:?}");
        if bytes[i + 1] == b'\'' {
            let start = i + 2;
            let end = start
                + rest[start..]
                    .find('\'')
                    .expect("arb_key never generates a single quote, so a closing one exists");
            steps.push(PathStep::Key(rest[start..end].to_string()));
            i = end + 2; // skip over "']"
        } else {
            let start = i + 1;
            let end = start
                + rest[start..]
                    .find(']')
                    .expect("index segment has a closing ]");
            let index: usize = rest[start..end].parse().expect("index segment is numeric");
            steps.push(PathStep::Index(index));
            i = end + 1;
        }
    }
    steps
}

/// Navigates `value` by `steps`, returning `None` as soon as a step doesn't
/// resolve (wrong container kind, missing key, or out-of-range index).
fn resolve<'v>(value: &'v Value, steps: &[PathStep]) -> Option<&'v Value> {
    let mut current = value;
    for step in steps {
        current = match step {
            PathStep::Key(key) => current.as_object()?.get(key)?,
            PathStep::Index(index) => current.as_array()?.get(*index)?,
        };
    }
    Some(current)
}

/// Returns `true` if the DeepDiff-style path `path` resolves to a node in
/// `value`.
fn resolves_in(value: &Value, path: &str) -> bool {
    resolve(value, &parse_path(path)).is_some()
}

/// The parent path (everything but the last step) and the last step of
/// `path`, e.g. `root['a']['b']` splits into `root['a']` and `Key("b")`.
fn split_last_step(path: &str) -> (Vec<PathStep>, PathStep) {
    let mut steps = parse_path(path);
    let last = steps
        .pop()
        .expect("a report path always has at least one step");
    (steps, last)
}

/// A JSON value's DeepDiff-reported "type" category, coarse enough to prove
/// (in)equality without duplicating `diff::python_type_name`'s exact string
/// table (private to that module, and already unit-tested there).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Kind {
    Null,
    Bool,
    Int,
    Float,
    Str,
    List,
    Dict,
}

fn kind_of(value: &Value) -> Kind {
    match value {
        Value::Null => Kind::Null,
        Value::Bool(_) => Kind::Bool,
        Value::Number(n) if n.is_f64() => Kind::Float,
        Value::Number(_) => Kind::Int,
        Value::String(_) => Kind::Str,
        Value::Array(_) => Kind::List,
        Value::Object(_) => Kind::Dict,
    }
}

/// Runs `diff`, asserting it succeeds (generated values are far shallower
/// than `DEFAULT_MAX_DEPTH`, so `Err` here would itself be a bug in either
/// this test file's bound or the engine).
fn diff_ok(a: &Value, b: &Value) -> Value {
    diff(a, b)
        .expect("generated depth is far below DEFAULT_MAX_DEPTH")
        .to_json_value()
}

/// The membership-delta invariant shared by `dictionary_item_added`'s and
/// `dictionary_item_removed`'s per-path assertions: `key` exists in
/// `has_key`'s parent object at `parent_steps`, and not in `lacks_key`'s
/// (either that side's parent isn't even an object, or it is but lacks the
/// key).
fn assert_membership_delta(
    has_key: &Value,
    lacks_key: &Value,
    parent_steps: &[PathStep],
    key: &str,
    path: &str,
) -> Result<(), TestCaseError> {
    let parent_with = resolve(has_key, parent_steps).and_then(Value::as_object);
    prop_assert!(
        parent_with.is_some_and(|map| map.contains_key(key)),
        "{key} at {path} does not exist in the expected parent object"
    );

    let parent_without = resolve(lacks_key, parent_steps).and_then(Value::as_object);
    prop_assert!(
        !parent_without.is_some_and(|map| map.contains_key(key)),
        "{key} at {path} unexpectedly exists in the other side's parent object"
    );
    Ok(())
}

/// The LCS-valid invariant shared by `iterable_item_added`'s and
/// `iterable_item_removed`'s per-path assertions.
///
/// This checks only that `index` is in range for `present_side`'s parent
/// array — deliberately *not* the stricter "tail surplus" form (also out of
/// range on the other side). That second half is not a valid invariant:
/// `array_diff`'s LCS list-matching path (see `crate::diff`'s "List diffing"
/// module doc section) can legitimately report an
/// `iterable_item_added`/`removed` at an index that is very much *in
/// range* on the other side too — e.g. a value that moved elsewhere in the
/// same list produces a remove at its old index and an add at its new one,
/// and both indices can easily be in range for both lists. Concretely,
/// `[1, 1.5, "a", null, true]` vs `[true, "a", null, 1.5, 1]` (see
/// `diff.rs`'s "List diffing" module doc) reports `iterable_item_removed`
/// at `root[1]` where `a` has length 5 — well in-range, not a surplus tail
/// at all.
///
/// What still holds unconditionally, regardless of which list algorithm
/// produced the finding: `index` resolves in `present_side`'s parent array,
/// and the finding's own `recorded_value` is exactly the value found
/// there — checking the *value*, not just the index bound, is strictly
/// more thorough than the invariant it replaces along that axis.
fn assert_index_resolves_to_recorded_value(
    present_side: &Value,
    parent_steps: &[PathStep],
    index: usize,
    recorded_value: &Value,
    path: &str,
) -> Result<(), TestCaseError> {
    let actual = resolve(present_side, parent_steps)
        .and_then(Value::as_array)
        .and_then(|items| items.get(index));
    prop_assert!(
        actual.is_some(),
        "index {index} at {path} is not in range for the expected parent array"
    );
    prop_assert_eq!(
        actual,
        Some(recorded_value),
        "recorded value at {} does not match the actual value at that index",
        path
    );
    Ok(())
}

proptest! {
    #![proptest_config(config())]

    /// (a) Reflexivity: diffing any value against itself is empty.
    ///
    /// This only ever exercises `values_equal`'s top-level equal-inputs
    /// fast path (`a == b` as a *whole*, checked once before any native
    /// recursion) — it never reaches the recursive engine's own
    /// equal-branches (`diff_at`'s dispatch, `object_diff`/`array_diff`
    /// recursing into equal children, `scalar_diff`/`numeric_diff`'s own
    /// equality checks), since identical top-level inputs always take the
    /// fast path home. See
    /// `shared_identical_substructure_alongside_an_unrelated_difference_reports_nothing_for_it`
    /// below for the companion property that forces the slow path instead.
    #[test]
    fn diff_of_a_value_with_itself_is_always_empty(value in arb_json_value()) {
        let report = diff_ok(&value, &value);
        prop_assert_eq!(report, serde_json::json!({}));
    }

    /// (a) Reflexivity companion: generalizes the hand-written "equal value
    /// at a shared key alongside an unrelated difference elsewhere" pattern
    /// (`diff.rs`'s
    /// `nested_equal_null_alongside_an_unrelated_change_produces_no_finding_for_it`
    /// and its list sibling) to arbitrary generated data. `a` and `b` are
    /// two objects forced apart by a `"differs"` key (`true` on one side,
    /// `false` on the other, so the top-level fast path above can never
    /// fire) that both also embed the identical, arbitrarily-shaped
    /// `shared` value at a `"shared"` key. This can only pass if the
    /// recursive engine's own equal-branches correctly report nothing for
    /// it — unlike the property above, it fails under a mutant that makes
    /// `scalar_diff` never short-circuit its own `equal` check.
    #[test]
    fn shared_identical_substructure_alongside_an_unrelated_difference_reports_nothing_for_it(
        shared in arb_json_value(),
    ) {
        let a = serde_json::json!({"shared": shared.clone(), "differs": true});
        let b = serde_json::json!({"shared": shared, "differs": false});

        let report = diff_ok(&a, &b);
        let categories = report.as_object().expect("to_json_value always returns an object");
        for entries in categories.values() {
            let entries = entries.as_object().expect("every category is a path-keyed map");
            for path in entries.keys() {
                prop_assert!(
                    !path.starts_with("root['shared']"),
                    "unexpected finding under the identical shared substructure at {path}"
                );
            }
        }
    }

    /// (b) Every reported path resolves in its expected side: added/
    /// iterable-added in `b`, removed/iterable-removed in `a`, `a`-side
    /// path of values_changed/type_changes in `a`, and its `b`-side
    /// location — `new_path` when the entry carries one, `path` itself
    /// otherwise — in `b`.
    ///
    /// This deliberately does *not* assert that `path` itself (the `a`-side
    /// path `values_changed`/`type_changes` are always keyed by) resolves in
    /// `b` too. That held only for the old index-aligned algorithm, which
    /// always compared same-index pairs; the LCS list-matching path
    /// (`crate::diff`'s "List diffing" module doc section) can pair an
    /// `a`-side index with a *different* `b`-side index and record the drift
    /// as [`crate::report::ValuesChangedEntry::new_path`] — and `path` (the
    /// old index) can end up entirely out of range for `b` once that drift
    /// is large enough. Concretely, `[0, 0, 3, 0, 1, 0]` vs `[4, 3, 0, 4]`
    /// reports a `values_changed` at `root[4]` (`a` has 6 elements) with
    /// `"new_path": "root[3]"` — `b` only has 4 elements, so `root[4]` does
    /// not resolve in it at all.
    #[test]
    fn every_reported_path_resolves_in_its_expected_side(
        a in arb_json_value(),
        b in arb_json_value(),
    ) {
        let report = diff_ok(&a, &b);
        let categories = report.as_object().expect("to_json_value always returns an object");

        for (category, entries) in categories {
            let entries = entries.as_object().expect("every category is a path-keyed map");
            for (path, entry) in entries {
                match category.as_str() {
                    "dictionary_item_added" | "iterable_item_added" => {
                        prop_assert!(
                            resolves_in(&b, path),
                            "{category} path {path} does not resolve in b"
                        );
                    }
                    "dictionary_item_removed" | "iterable_item_removed" => {
                        prop_assert!(
                            resolves_in(&a, path),
                            "{category} path {path} does not resolve in a"
                        );
                    }
                    "values_changed" | "type_changes" => {
                        prop_assert!(
                            resolves_in(&a, path),
                            "{category} path {path} does not resolve in a"
                        );
                        let b_side_path = entry
                            .get("new_path")
                            .and_then(Value::as_str)
                            .unwrap_or(path.as_str());
                        prop_assert!(
                            resolves_in(&b, b_side_path),
                            "{category} path {path}'s b-side location {b_side_path} does not resolve in b"
                        );
                    }
                    other => panic!("unexpected report category {other}"),
                }
            }
        }
    }

    /// (c) `dictionary_item_added` keys exist in `b`'s parent object, and
    /// not in `a`'s (either the parent itself is missing/not-an-object on
    /// the `a` side, or it exists but lacks the key).
    #[test]
    fn dictionary_item_added_keys_exist_in_b_parent_and_not_in_a_parent(
        a in arb_json_value(),
        b in arb_json_value(),
    ) {
        let report = diff_ok(&a, &b);
        if let Some(added) = report.get("dictionary_item_added").and_then(Value::as_object) {
            for path in added.keys() {
                let (parent_steps, last) = split_last_step(path);
                let PathStep::Key(key) = last else {
                    panic!("dictionary_item_added path {path} does not end in a key");
                };
                assert_membership_delta(&b, &a, &parent_steps, &key, path)?;
            }
        }
    }

    /// (c) `dictionary_item_removed` keys exist in `a`'s parent object, and
    /// not in `b`'s — the mirror of the added case above.
    #[test]
    fn dictionary_item_removed_keys_exist_in_a_parent_and_not_in_b_parent(
        a in arb_json_value(),
        b in arb_json_value(),
    ) {
        let report = diff_ok(&a, &b);
        if let Some(removed) = report.get("dictionary_item_removed").and_then(Value::as_object) {
            for path in removed.keys() {
                let (parent_steps, last) = split_last_step(path);
                let PathStep::Key(key) = last else {
                    panic!("dictionary_item_removed path {path} does not end in a key");
                };
                assert_membership_delta(&a, &b, &parent_steps, &key, path)?;
            }
        }
    }

    /// (c) `iterable_item_added` indices resolve in `b`'s parent array to
    /// exactly the recorded value.
    ///
    /// Asserts each added index resolves in `b` to exactly the recorded
    /// value — deliberately *not* the stricter "surplus tail of `b` beyond
    /// `a`" form (also out of range on `a`'s side), which does not hold
    /// under the LCS list-matching path; see
    /// [`assert_index_resolves_to_recorded_value`]'s doc.
    #[test]
    fn iterable_item_added_indices_resolve_to_the_recorded_value_in_b(
        a in arb_json_value(),
        b in arb_json_value(),
    ) {
        let report = diff_ok(&a, &b);
        if let Some(added) = report.get("iterable_item_added").and_then(Value::as_object) {
            for (path, recorded_value) in added {
                let (parent_steps, last) = split_last_step(path);
                let PathStep::Index(index) = last else {
                    panic!("iterable_item_added path {path} does not end in an index");
                };
                assert_index_resolves_to_recorded_value(&b, &parent_steps, index, recorded_value, path)?;
            }
        }
    }

    /// (c) `iterable_item_removed` indices resolve in `a`'s parent array to
    /// exactly the recorded value — the mirror of the added case.
    ///
    /// The mirror of the added case; the stricter "surplus tail of `a`
    /// beyond `b`" form does not hold under the LCS list-matching path — see
    /// [`assert_index_resolves_to_recorded_value`]'s doc.
    #[test]
    fn iterable_item_removed_indices_resolve_to_the_recorded_value_in_a(
        a in arb_json_value(),
        b in arb_json_value(),
    ) {
        let report = diff_ok(&a, &b);
        if let Some(removed) = report.get("iterable_item_removed").and_then(Value::as_object) {
            for (path, recorded_value) in removed {
                let (parent_steps, last) = split_last_step(path);
                let PathStep::Index(index) = last else {
                    panic!("iterable_item_removed path {path} does not end in an index");
                };
                assert_index_resolves_to_recorded_value(&a, &parent_steps, index, recorded_value, path)?;
            }
        }
    }

    /// (c) `type_changes` entries genuinely change kind (never int/int,
    /// dict/dict, etc — that would be `values_changed` or empty instead).
    #[test]
    fn type_changes_entries_have_genuinely_different_kinds(
        a in arb_json_value(),
        b in arb_json_value(),
    ) {
        let report = diff_ok(&a, &b);
        if let Some(entries) = report.get("type_changes").and_then(Value::as_object) {
            for entry in entries.values() {
                let old_kind = kind_of(&entry["old_value"]);
                let new_kind = kind_of(&entry["new_value"]);
                prop_assert_ne!(old_kind, new_kind);
            }
        }
    }

    /// (c) `values_changed` entries keep the same kind but differ in value
    /// (a same-kind, same-value pair would report no finding at all).
    #[test]
    fn values_changed_entries_keep_kind_but_differ_in_value(
        a in arb_json_value(),
        b in arb_json_value(),
    ) {
        let report = diff_ok(&a, &b);
        if let Some(entries) = report.get("values_changed").and_then(Value::as_object) {
            for entry in entries.values() {
                let old_value = &entry["old_value"];
                let new_value = &entry["new_value"];
                prop_assert_eq!(kind_of(old_value), kind_of(new_value));
                prop_assert_ne!(old_value, new_value);
            }
        }
    }

    /// (d) Determinism: diffing the same pair twice yields byte-identical
    /// (structurally identical) reports.
    #[test]
    fn diff_result_is_deterministic_across_repeated_calls(
        a in arb_json_value(),
        b in arb_json_value(),
    ) {
        let first = diff_ok(&a, &b);
        let second = diff_ok(&a, &b);
        prop_assert_eq!(first, second);
    }

    /// (d) Determinism: the report is unaffected by the insertion order used
    /// to build a logically-identical `serde_json::Map` on one side.
    #[test]
    fn diff_result_is_unaffected_by_dict_key_insertion_order(
        entries in prop::collection::hash_map(arb_key(), arb_json_value(), 1..MAX_COLLECTION_BRANCH as usize),
        other in arb_json_value(),
    ) {
        let entries: Vec<(String, Value)> = entries.into_iter().collect();

        let forward: Map<String, Value> = entries.iter().cloned().collect();
        let backward: Map<String, Value> = entries.iter().rev().cloned().collect();
        // Building from two different insertion orders must still produce
        // the same logical map (the property this test exists to check, one
        // level below diffing it).
        prop_assert_eq!(&forward, &backward);

        let forward_report = diff_ok(&Value::Object(forward), &other);
        let backward_report = diff_ok(&Value::Object(backward), &other);
        prop_assert_eq!(forward_report, backward_report);
    }
}

/// A trivial sanity check that [`parse_path`]/[`resolve`] themselves behave
/// as expected on hand-written examples, independent of any generated data —
/// this is test-support code, not the diff engine, but it is exactly the
/// kind of helper that could silently make every property above vacuously
/// true if it were broken (e.g. always returning `Some`).
#[test]
fn path_resolver_helper_matches_hand_written_examples() {
    let value = serde_json::json!({"a": [1, {"b c": 2}], "": 3});

    assert_eq!(resolve(&value, &parse_path("root")), Some(&value));
    assert_eq!(resolve(&value, &parse_path("root['a']")), value.get("a"));
    assert_eq!(
        resolve(&value, &parse_path("root['a'][1]['b c']")),
        Some(&Value::from(2))
    );
    assert_eq!(
        resolve(&value, &parse_path("root['']")),
        Some(&Value::from(3))
    );
    assert_eq!(resolve(&value, &parse_path("root['missing']")), None);
    assert_eq!(resolve(&value, &parse_path("root['a'][99]")), None);
    assert_eq!(
        resolve(&value, &parse_path("root['a']['not-an-index']")),
        None
    );
}
