"""Golden-corpus parity: onix's Python bindings vs real DeepDiff.

Reuses the repository's existing hand-designed golden corpus
(``tests/golden/`` at the repo root, generated by ``scripts/gen_goldens.py``
against pinned ``deepdiff==9.1.0``) rather than maintaining a second,
Python-only case list — every case directory holds ``a.json``/``b.json``/
``expected.json``/``options.json``, exactly as the Rust golden test
(``crates/onix-core/tests/golden.rs``) reads them.

The two input files are decoded through ``scripts/golden_tags.py`` (on the
path via this package's pytest configuration), which turns the corpus's tagged
objects back into the Python values they stand for — a tuple today. Both
engines then see the same live objects.
"""

import json
from pathlib import Path

import pytest
from deepdiff import DeepDiff as RealDeepDiff
from golden_tags import TaggedValue, decode_tags

from deepdiff_rs import DeepDiff as OnixDeepDiff

GOLDEN_ROOT = Path(__file__).resolve().parents[3] / "tests" / "golden"

# Mirrors crates/onix-core/tests/golden.rs's KNOWN_DIVERGENT_CASES: DeepDiff's
# path rendering is not injective on adversarial keys, so which finding
# survives an insertion-order-dependent collapse is an accepted, documented
# divergence rather than a bug onix is expected to reproduce byte-for-byte.
KNOWN_DIVERGENT_CASES = {"path_rendering_collision"}


def _case_names() -> list[str]:
    """
    List every golden case directory name, sorted for a deterministic order.

    :return: Sorted case directory names under ``tests/golden/``.
    """
    return sorted(entry.name for entry in GOLDEN_ROOT.iterdir() if entry.is_dir())


def _read_json(path: Path) -> TaggedValue:
    """
    Read and parse a JSON fixture file.

    :param path: Path to the JSON file.
    :return: The parsed JSON value.
    """
    return json.loads(path.read_text())


def _read_case_input(path: Path) -> TaggedValue:
    """
    Read one of a case's two input files as the Python value it stands for.

    :param path: Path to ``a.json`` or ``b.json``.
    :return: The decoded value, with tagged objects turned back into Python objects.
    """
    return decode_tags(_read_json(path))


def _case_options(case_dir: Path) -> dict[str, TaggedValue]:
    """
    Read a case's ``options.json``, defaulting to ``{}`` if absent.

    :param case_dir: The golden case's directory.
    :return: The parsed options, or an empty dict if the file is missing.
    """
    options_path = case_dir / "options.json"

    if not options_path.exists():
        return {}

    return _read_json(options_path)


@pytest.mark.parametrize(
    "case_name",
    [name for name in _case_names() if name not in KNOWN_DIVERGENT_CASES],
)
def test_golden_case_matches_real_deepdiff(case_name: str) -> None:
    """
    Assert onix's bindings match real DeepDiff's ``to_json()`` on a golden case.

    :param case_name: The golden case directory name (parametrized over the
        whole corpus, minus :data:`KNOWN_DIVERGENT_CASES`).
    """
    case_dir = GOLDEN_ROOT / case_name
    a = _read_case_input(case_dir / "a.json")
    b = _read_case_input(case_dir / "b.json")
    ignore_order = bool(_case_options(case_dir).get("ignore_order", False))

    expected = json.loads(RealDeepDiff(a, b, ignore_order=ignore_order, verbose_level=2).to_json())
    actual = json.loads(OnixDeepDiff(a, b, ignore_order=ignore_order).to_json())

    assert actual == expected


def test_golden_corpus_is_non_empty() -> None:
    """Guard against a silently empty parametrize list (e.g. a bad path)."""
    assert len(_case_names()) > len(KNOWN_DIVERGENT_CASES)
