"""Tests for `generate_fixtures.py`: determinism, exact counts, and shape."""

import json
from pathlib import Path

import pyarrow.parquet as pq
import pytest

from generate_fixtures import CATEGORY_VALUES, PAYLOAD_MAX_LEN, PAYLOAD_MIN_LEN, generate

SEED = 12345


# Determinism tests
@pytest.mark.parametrize("n_rows", [1_000, pytest.param(100_000, marks=pytest.mark.slow)])
def test_regeneration_is_byte_identical(n_rows: int, tmp_path: Path) -> None:
    """Two runs of `generate` with the same rows/seed produce identical bytes, at every tested size."""
    out1, out2 = tmp_path / "run1", tmp_path / "run2"
    generate(n_rows, SEED, out1)
    generate(n_rows, SEED, out2)

    for name in ("a.parquet", "b.parquet", "manifest.json"):
        assert (out1 / name).read_bytes() == (out2 / name).read_bytes()


def test_different_seeds_produce_different_output(tmp_path: Path) -> None:
    """A different seed changes the generated bytes (rules out a constant-output bug)."""
    out1, out2 = tmp_path / "run1", tmp_path / "run2"
    generate(1000, SEED, out1)
    generate(1000, SEED + 1, out2)

    assert (out1 / "a.parquet").read_bytes() != (out2 / "a.parquet").read_bytes()


# Sidecar count tests
def test_sidecar_counts_match_actual_row_counts(tmp_path: Path) -> None:
    """Every sidecar count matches what's actually in the parquet files."""
    out = tmp_path / "fixture"
    manifest = generate(1000, SEED, out)

    a = pq.read_table(out / "a.parquet")
    b = pq.read_table(out / "b.parquet")

    assert a.num_rows == 1000
    assert b.num_rows == 1000 - manifest["rows_deleted"] + manifest["rows_added"]
    assert manifest["rows_deleted"] + manifest["rows_modified_amount"] + manifest["rows_modified_payload"] + manifest[
        "rows_unchanged"
    ] == 1000

    manifest_on_disk = json.loads((out / "manifest.json").read_text())
    assert manifest_on_disk == manifest


def test_manifest_schema_changes_list_the_three_documented_changes(tmp_path: Path) -> None:
    """The sidecar's `schema_changes` names exactly category, ts, and note."""
    manifest = generate(1000, SEED, tmp_path / "fixture")
    changed_columns = {entry["column"] for entry in manifest["schema_changes"]}
    assert changed_columns == {"category", "ts", "note"}


# Shape / value tests
def test_ids_unique_and_ascending_on_both_sides(tmp_path: Path) -> None:
    """`id` is unique and strictly ascending in both a.parquet and b.parquet."""
    out = tmp_path / "fixture"
    generate(1000, SEED, out)

    for name in ("a.parquet", "b.parquet"):
        ids = pq.read_table(out / name).column("id").to_pylist()
        assert ids == sorted(ids)
        assert len(set(ids)) == len(ids)


def test_no_duplicate_keys_by_construction(tmp_path: Path) -> None:
    """The fixture never introduces a repeated id on either side (documented scope)."""
    out = tmp_path / "fixture"
    manifest = generate(1000, SEED, out)
    assert manifest["duplicate_keys"] == 0


def test_a_schema_matches_the_documented_five_columns(tmp_path: Path) -> None:
    """a.parquet has exactly the five documented columns and types."""
    out = tmp_path / "fixture"
    generate(1000, SEED, out)
    schema = pq.read_schema(out / "a.parquet")

    assert schema.names == ["id", "ts", "category", "amount", "payload"]
    assert str(schema.field("ts").type) == "timestamp[us, tz=UTC]"
    assert str(schema.field("amount").type) == "decimal128(18, 4)"


def test_b_schema_matches_the_mutated_shape(tmp_path: Path) -> None:
    """b.parquet has the retyped `category`/`ts`, plus the new `note` column."""
    out = tmp_path / "fixture"
    generate(1000, SEED, out)
    schema = pq.read_schema(out / "b.parquet")

    assert schema.names == ["id", "ts", "category", "amount", "payload", "note"]
    assert str(schema.field("ts").type) == "timestamp[ms, tz=UTC]"
    assert str(schema.field("category").type) == "dictionary<values=string, indices=int32, ordered=0>"


def test_category_values_come_from_the_fixed_20_value_pool(tmp_path: Path) -> None:
    """Every `category` value on both sides is one of the 20 documented values."""
    out = tmp_path / "fixture"
    generate(2000, SEED, out)
    a_categories = set(pq.read_table(out / "a.parquet").column("category").to_pylist())
    b_categories = set(pq.read_table(out / "b.parquet").column("category").to_pylist())

    assert a_categories <= set(CATEGORY_VALUES)
    assert b_categories <= set(CATEGORY_VALUES)


def test_payload_lengths_are_within_the_documented_bounds(tmp_path: Path) -> None:
    """Every `payload` string is between 20 and 200 characters, both sides."""
    out = tmp_path / "fixture"
    generate(2000, SEED, out)

    for name in ("a.parquet", "b.parquet"):
        lengths = [len(p) for p in pq.read_table(out / name).column("payload").to_pylist()]
        assert min(lengths) >= PAYLOAD_MIN_LEN
        assert max(lengths) <= PAYLOAD_MAX_LEN


def test_added_rows_have_note_added_and_carried_over_rows_have_null(tmp_path: Path) -> None:
    """The new column's values match the documented rule: null unless newly added."""
    out = tmp_path / "fixture"
    generate(1000, SEED, out)
    b = pq.read_table(out / "b.parquet").to_pylist()
    original_ids = set(range(1000))

    for row in b:
        if row["id"] in original_ids:
            assert row["note"] is None
        else:
            assert row["note"] == "added"


def test_modified_rows_change_exactly_one_of_amount_or_payload(tmp_path: Path) -> None:
    """A row flagged as amount-modified keeps its original payload, and vice versa."""
    out = tmp_path / "fixture"
    generate(1000, SEED, out)
    a_rows = {row["id"]: row for row in pq.read_table(out / "a.parquet").to_pylist()}
    b_rows = {row["id"]: row for row in pq.read_table(out / "b.parquet").to_pylist()}

    changed_both = 0

    for key, a_row in a_rows.items():
        b_row = b_rows.get(key)

        if b_row is None:
            continue

        amount_changed = a_row["amount"] != b_row["amount"]
        payload_changed = a_row["payload"] != b_row["payload"]

        if amount_changed and payload_changed:
            changed_both += 1

    assert changed_both == 0


# Boundary tests
def test_generate_with_a_single_row(tmp_path: Path) -> None:
    """A 1-row fixture doesn't crash even though every mutation count rounds to 0."""
    out = tmp_path / "fixture"
    manifest = generate(1, SEED, out)

    assert manifest["rows_deleted"] == 0
    assert manifest["rows_added"] == 0
    assert pq.read_table(out / "a.parquet").num_rows == 1
    assert pq.read_table(out / "b.parquet").num_rows == 1


def test_generate_overwrites_a_previous_run_in_the_same_directory(tmp_path: Path) -> None:
    """Regenerating into an existing directory replaces the previous parquet files."""
    out = tmp_path / "fixture"
    generate(1000, SEED, out)
    generate(500, SEED, out)

    assert pq.read_table(out / "a.parquet").num_rows == 500
