"""Tests for `generate_fixtures.py`'s `wide` kind (#84): determinism, exact
counts, and the full cell-type-surface schema -- see its own module
docstring for the column set and mutation mix this exercises.
"""

import json
from pathlib import Path

import pyarrow.parquet as pq
import pytest

from generate_fixtures import generate

SEED = 424242

_EXPECTED_A_TYPES: dict[str, str] = {
    "id": "int64",
    "i8": "int8",
    "i16": "int16",
    "i32": "int32",
    "i64": "int64",
    "u8": "uint8",
    "u16": "uint16",
    "u32": "uint32",
    "u64": "uint64",
    "f32": "float",
    "f64": "double",
    "float16_col": "halffloat",
    "dec_scale4": "decimal128(18, 4)",
    "dec_scale10": "decimal128(38, 10)",
    "dec256": "decimal256(38, 10)",
    "decimal32_col": "decimal32(5, 2)",
    "decimal64_col": "decimal64(10, 2)",
    "utf8_col": "string",
    "large_utf8_col": "large_string",
    "utf8_view_col": "string_view",
    "binary_col": "binary",
    "binary_view_col": "binary_view",
    "fixed_size_binary_col": "fixed_size_binary[4]",
    "bool_col": "bool",
    "date32_col": "date32[day]",
    "date64_millis": "int64",
    "time32_col": "time32[ms]",
    "time64_col": "time64[us]",
    "dur_a": "duration[s]",
    "dur_b": "duration[ns]",
    "interval_months": "int32",
    "interval_days": "int32",
    "interval_nanos": "int64",
    "category": "string",
    "ts_cast": "timestamp[ns, tz=UTC]",
}


def test_wide_regeneration_is_byte_identical(tmp_path: Path) -> None:
    """Two `wide` runs with the same rows/seed produce identical bytes."""
    out1, out2 = tmp_path / "run1", tmp_path / "run2"
    generate(2000, SEED, out1, kind="wide")
    generate(2000, SEED, out2, kind="wide")

    for name in ("a.parquet", "b.parquet", "manifest.json"):
        assert (out1 / name).read_bytes() == (out2 / name).read_bytes()


def test_wide_different_seeds_produce_different_output(tmp_path: Path) -> None:
    """A different seed changes the generated bytes."""
    out1, out2 = tmp_path / "run1", tmp_path / "run2"
    generate(2000, SEED, out1, kind="wide")
    generate(2000, SEED + 1, out2, kind="wide")

    assert (out1 / "a.parquet").read_bytes() != (out2 / "a.parquet").read_bytes()


def test_wide_a_schema_covers_every_documented_type(tmp_path: Path) -> None:
    """`a.parquet`'s schema has exactly the documented columns and types."""
    out = tmp_path / "fixture"
    generate(2000, SEED, out, kind="wide")
    schema = pq.read_schema(out / "a.parquet")

    assert schema.names == list(_EXPECTED_A_TYPES)
    for name, expected_type in _EXPECTED_A_TYPES.items():
        assert str(schema.field(name).type) == expected_type, name


def test_wide_b_schema_has_the_four_schema_changes(tmp_path: Path) -> None:
    """`b.parquet` retypes `category`/`dec_scale4`/`ts_cast` and adds `extra`."""
    out = tmp_path / "fixture"
    generate(2000, SEED, out, kind="wide")
    schema = pq.read_schema(out / "b.parquet")

    assert schema.names == [*_EXPECTED_A_TYPES, "extra"]
    assert str(schema.field("category").type) == "dictionary<values=string, indices=int32, ordered=0>"
    assert str(schema.field("dec_scale4").type) == "decimal128(18, 6)"
    assert str(schema.field("ts_cast").type) == "timestamp[us]"
    assert str(schema.field("extra").type) == "string"


def test_wide_manifest_schema_changes_list_the_four_documented_changes(tmp_path: Path) -> None:
    """The sidecar's `schema_changes` names exactly the four retyped/added columns."""
    manifest = generate(2000, SEED, tmp_path / "fixture", kind="wide")
    changed_columns = {entry["column"] for entry in manifest["schema_changes"]}
    assert changed_columns == {"category", "dec_scale4", "ts_cast", "extra"}


def test_wide_sidecar_counts_match_actual_row_counts(tmp_path: Path) -> None:
    """Every sidecar row count matches what's actually in the parquet files."""
    out = tmp_path / "fixture"
    manifest = generate(5000, SEED, out, kind="wide")

    a = pq.read_table(out / "a.parquet")
    b = pq.read_table(out / "b.parquet")

    assert a.num_rows == 5000
    assert b.num_rows == 5000 - manifest["rows_deleted"] + manifest["rows_added"]
    manifest_on_disk = json.loads((out / "manifest.json").read_text())
    assert manifest_on_disk == manifest


def test_wide_cells_type_changed_equals_surviving_rows(tmp_path: Path) -> None:
    """`ts_cast`'s zone-awareness change makes every surviving row `type_changed`."""
    manifest = generate(5000, SEED, tmp_path / "fixture", kind="wide")
    assert manifest["cells_type_changed"] == manifest["rows"] - manifest["rows_deleted"]


def test_wide_ts_cast_is_never_null_and_never_independently_modified(tmp_path: Path) -> None:
    """`ts_cast` carries no null and no `value_changed` count of its own."""
    out = tmp_path / "fixture"
    manifest = generate(5000, SEED, out, kind="wide")
    assert "ts_cast" not in manifest["value_changed_per_column"]
    for side in ("a.parquet", "b.parquet"):
        assert None not in pq.read_table(out / side).column("ts_cast").to_pylist()


def test_wide_value_changed_columns_carry_a_positive_count(tmp_path: Path) -> None:
    """Every column tracked as `value_changed` reports a nonzero realized count."""
    manifest = generate(20_000, SEED, tmp_path / "fixture", kind="wide")
    assert manifest["value_changed_per_column"]
    assert all(count > 0 for count in manifest["value_changed_per_column"].values())


def test_wide_value_changed_covers_float16_decimal32_decimal64_and_the_view_types(tmp_path: Path) -> None:
    """The six added types each carry their own `value_changed` count."""
    manifest = generate(20_000, SEED, tmp_path / "fixture", kind="wide")
    for column in (
        "float16_col", "decimal32_col", "decimal64_col", "utf8_view_col", "binary_view_col", "fixed_size_binary_col",
    ):
        assert manifest["value_changed_per_column"][column] > 0


def test_wide_became_null_and_became_non_null_are_tracked_for_i16_and_large_utf8(tmp_path: Path) -> None:
    """The two null-transition columns report positive counts both ways."""
    manifest = generate(20_000, SEED, tmp_path / "fixture", kind="wide")
    for column in ("i16", "large_utf8_col"):
        assert manifest["became_null_per_column"][column] > 0
        assert manifest["became_non_null_per_column"][column] > 0


def test_wide_interval_components_share_one_null_mask(tmp_path: Path) -> None:
    """`interval_months`/`_days`/`_nanos` are null together, row by row."""
    out = tmp_path / "fixture"
    generate(5000, SEED, out, kind="wide")
    table = pq.read_table(out / "a.parquet")
    months = table.column("interval_months").to_pylist()
    days = table.column("interval_days").to_pylist()
    nanos = table.column("interval_nanos").to_pylist()

    for m, d, n in zip(months, days, nanos, strict=True):
        null_flags = {m is None, d is None, n is None}
        assert len(null_flags) == 1


def test_wide_date64_millis_is_whole_day_aligned(tmp_path: Path) -> None:
    """`date64_millis` values are always a whole number of days, Arrow's `Date64` contract."""
    out = tmp_path / "fixture"
    generate(5000, SEED, out, kind="wide")
    values = pq.read_table(out / "a.parquet").column("date64_millis").to_pylist()
    for value in values:
        if value is not None:
            assert value % 86_400_000 == 0


def test_wide_float_columns_include_nan_and_signed_zero(tmp_path: Path) -> None:
    """`f32`/`f64` occasionally draw NaN and `-0.0`, per the module docstring."""
    out = tmp_path / "fixture"
    generate(5000, SEED, out, kind="wide")
    f64 = pq.read_table(out / "a.parquet").column("f64").to_pylist()
    has_nan = any(v is not None and v != v for v in f64)  # noqa: PLR0124 (NaN self-inequality)
    has_neg_zero = any(v == 0.0 and str(v) == "-0.0" for v in f64 if v is not None)
    assert has_nan
    assert has_neg_zero


@pytest.mark.parametrize("rows", [0, 1])
def test_wide_generate_with_zero_or_one_row(rows: int, tmp_path: Path) -> None:
    """A near-empty `wide` fixture doesn't crash even though every rate rounds to 0."""
    out = tmp_path / "fixture"
    manifest = generate(rows, SEED, out, kind="wide")

    assert manifest["rows_deleted"] == 0
    assert manifest["rows_added"] == 0
    assert pq.read_table(out / "a.parquet").num_rows == rows
